apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus
    app.kubernetes.io/part-of: test-application
  name: devfile-sample-code-with-quarkus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus
    spec:
      containers:
      - image: quay.io/rcerven_rhtaptest/default/test-application/devfile-sample-code-with-quarkus@sha256:3b0ef4894cdc8f3024daf4433b02daec58026ab6cbac1c18ab93b2e115a791ac
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
